marmelab/gremlins.js

- README.md
at the end of the line "var horde = gremlins.createHorde()".
> README.md Missing semicolon added 

- src/mogwais/gizmo.js
> typo in gizmo.js fixed

- Makefile
- examples/basic/basic.js
- src/index.js
- src/strategies/allTogether.js
- src/strategies/bySpecies.js
- src/strategies/distribution.js
- src/utils/executeInSeries.js
- src/utils/wait.js
> Migrate callbacks to promises

- package-lock.json
- package.json
If you want to know more about this convention, https://www.conventionalcommits.org/
> feat: add commitlint convention

- examples/basic/basic.css
- examples/basic/index.html
- package-lock.json
- package.json
- webpack.demo.js
> feat: update babel, webpack and chance dep

- bookmarklet/index.css
- bookmarklet/index.html
> Custom bookmarklet

- src/mogwais/alert.spec.js
- src/mogwais/fps.spec.js
- src/species/clicker.js
- src/species/clicker.spec.js
- src/species/formFiller.spec.js
- src/species/scroller.spec.js
- src/species/toucher.js
- src/species/toucher.spec.js
- src/species/typer.spec.js
- src/utils/executeInSeries.js
> Add species tests

- src/strategies/allTogether.js
- src/strategies/allTogether.spec.js
- src/strategies/bySpecies.js
- src/strategies/bySpecies.spec.js
- src/strategies/distribution.js
- src/strategies/distribution.spec.js
> Add strategies test

- bookmarklet/index.html
> Expose gremlins in bookmarklet page

- src/species/formFiller.js
> Fix textarea event

- src/utils/executeInSeries.js
- src/utils/executeInSeries.spec.js
> Refacto executeInSeries function

- src/species/toucher.js
- src/species/toucher.spec.js
> fix: toucher log test

- Makefile
- bookmarklet/index.html
- package-lock.json
> fix: change next to master branch

- src/species/clicker.js
- src/species/toucher.js
- src/species/typer.js
**What**: https://github.com/marmelab/gremlins.js/issues/159
**Why**: Min cannot be greater than max
**How**: Get max of 0 and client size
**Checklist**:
-   [x] toucher
-   [x] typer
-   [x] clicker
> fix: chance RangeError

- package-lock.json
- package.json
**What**: Bump standard-version to 8.0.2
**Why**: Security update
> feat: bump standard-version to 8.0.2

- .eslintrc.js
- .gitignore
- .travis.yml
- Makefile
- README.md
- cypress.json
- cypress/fixtures/example.json
- cypress/integration/formFiller.spec.js
- cypress/pages/formFiller.html
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- package-lock.json
- package.json
**What**: Add first cypress test to formFiller 
**Why**: To make sure we don't break anything with cypress integration
**Checklist**:
-   [x] Add 1st cypress test
-   [x] Add cypress tests to travis build
-   [x] Update readme to use cypress promise instead of native promise
> Add first cypress test for formFiller

- README.md
**What**:
- change PR link
- each badge in one line
**Why**:
- go to PR tab to create PR instead of `http://makeapullrequest.com`
- the badge is clearly (one badge on line in code, but still they in one line after render)
**How**:
**Checklist**:
-   [x] Documentation added to the README.md file
-   [ ] Tests
-   [ ] Typescript definitions updated
-   [ ] RFR, Ready for review label
> Update link PR

- src/species/clicker.js
**What**: In the "clicker" species, the variable "window" wasn't being used in every place
**Why**: When using a tested window the clicker wouldn't work, for example when using Cypress
**How**:  "window." was added before "document."
**Checklist**:
-   [x] Documentation added to the README.md file
-   [X] Tests
-   [ ] Typescript definitions updated
-   [ ] RFR, Ready for review label
> Corrected window

- README.md
**What**: Fix incorrect documentation in README: You can't do `horde.createHorde()`
**Why**: Because it's good to have a correct documentation 😬
**How**: Updated the README
**Checklist**:
-   [x] Documentation added to the README.md file
-   [x] Tests
-   [x] Typescript definitions updated
-   [x] RFR, Ready for review label
> Fix documentation in README

- README.md
**What**: Fixes https://github.com/marmelab/gremlins.js/issues/175
**Why**: Playwright is a browser automation library mainly focusing on tests that is getting popular
**How**: Updating README.md with a Playwright example
**Checklist**:
-   [x] Documentation added to the README.md file
-   [x] Tests/lint
-   [ ] ~Typescript definitions updated~
-   [ ] ~RFR, Ready for review label~
> feat: update readme with Playwright usage
